Fix multiple compilation errors in debug and function packages
Fixed the following compilation errors:

1. engine/debug/debug_session.go:499:1 - Removed orphaned import statement
   - Added "fmt" to imports at top of file
   - Removed duplicate "import fmt" at line 499

2. engine/function/common_execution.go:96 - Fixed undefined severity constants
   - Changed types.SeverityCritical to types.ErrorSeverityCritical
   - Changed types.SeverityError to types.ErrorSeverityError

3. engine/function/csharpfuncs_enhanced.go - Multiple fixes:
   - Line 87: Fixed NewTimeoutError call - changed (string, error) to (string, time.Duration)
   - Line 102: Fixed NewScriptError call - added scriptType parameter ("C#")
   - Line 141: Fixed NewScriptError call - added scriptType parameter
   - Line 157: Changed Log.Performance to Log.Info (Performance method doesn't exist)
   - Line 229: Fixed NewScriptError call - added scriptType parameter
   - Line 290: Fixed severity constants (ErrorSeverityCritical, ErrorSeverityError)

4. engine/function/goexprfuncs_enhanced.go - Fixed NewScriptError calls:
   - Line 65: Added scriptType parameter ("GoExpression")
   - Line 125: Added scriptType parameter
   - Line 182: Added scriptType parameter

All NewScriptError calls now use correct signature: (scriptType, message, error)
All severity constants now use correct names: ErrorSeverityCritical, ErrorSeverityError
All NewTimeoutError calls now use correct signature: (operation, timeout)